export const OBTER_TODAS_REQUISICAO = "OBTER_TODAS_REQUISICAO";
export const OBTER_TODAS_SUCESSO = "OBTER_TODAS_SUCESSO";
export const OBTER_TODOS_ERRO = "OBTER_TODOS_ERRO";
export const REMOVER_REQUISICOES = "REMOVER_REQUISICOES";
export const REMOVER_SUCESSO = "REMOVER_SUCESSO";
export const REMOVER_ERRO = "REMOVER_ERRO";
