export const LOGINREQUEST = 'LOGINREQUEST';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAILURE = 'LOGINFAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTERREQUEST = 'REGISTERREQUEST';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTERFAILURE = 'REGISTERFAILURE';
export const SETACCOUNTINFO = 'SETACCOUNTINFO';
