export const ESTADO_PNL_CREATE = 'ESTADO_PNL_CREATE';
export const ESTADO_PNL_LIST = 'ESTADO_PNL_LIST';
export const CRIAR_EVENTO = 'CRIAR_EVENTO';
export const EVENTOS_INSTITUICAO = 'EVENTOS_INSTITUICAO';
export const DELETAR_EVENTO = 'DELETAR_EVENTO';