export const ESTADO_PNL_CREATE = 'ESTADO_PNL_CREATE';
export const ESTADO_PNL_LIST = 'ESTADO_PNL_LIST';
export const VISIBLE_PNL_CREATE = 'VISIBLE_PNL_CREATE';
export const CRIAR_EVENTO = 'CRIAR_EVENTO';
export const EVENTOS_INSTITUICAO = 'EVENTOS_INSTITUICAO';
export const DELETAR_EVENTO = 'DELETAR_EVENTO';
export const EVENTO_EDITAR = 'EVENTO_EDITAR';
export const ATUALIZAR_EVENTO = 'ATUALIZAR_EVENTO';