export const GETALLREQUEST = "GETALLREQUEST";
export const GETALLSUCCESS = "GETALLSUCCESS";
export const GETALLFAILURE = "GETALLFAILURE";
export const DELETEREQUEST = "DELETEREQUEST";
export const DELETESUCCESS = "DELETESUCCESS";
export const DELETEFAILURE = "DELETEFAILURE";
