export const DEFINIR_MENSAGENS = 'DEFINIR_MENSAGENS';
export const REMOVER_MENSAGEM = 'REMOVER_MENSAGEM';
export const ATUALIZAR_MENSAGEM = 'ATUALIZAR_MENSAGEM';
export const ACRESCENTAR_MENSAGEM = 'ACRESCENTAR_MENSAGEM';
