export const DEFINIR_MENSAGEM = 'DEFINIR_MENSAGEM';
export const DELETE_MENSAGEM = 'DELETE_MENSAGEM';
export const ATUALIZAR_MENSAGEM = 'ATUALIZAR_MENSAGEM';
export const ACRESCENTAR_MENSAGEM = 'ACRESCENTAR_MENSAGEM';
