-- INSERT INTO notificacao.usuario (usuario_id, descricao, is_ativo) VALUES (1, 'usuario1', true);
-- INSERT INTO notificacao.plataforma (plataforma_id, descricao, is_ativo) VALUES (1, 'plataforma web', true);
-- INSERT INTO notificacao.plataforma (plataforma_id, descricao, is_ativo) VALUES (2, 'plataforma 2', true);
-- INSERT INTO notificacao.sistema (sistema_id, descricao, is_ativo) VALUES (1, 'salic', true);
