export const SET_PLATAFORMA = 'SET_PLATAFORMA';
export const DELETE_PLATAFORMA = 'DELETE_PLATAFORMA';
export const ATUALIZAR_PLATAFORMA = 'ATUALIZAR_PLATAFORMA';
export const ACRESCENTAR_PLATAFORMA = 'ACRESCENTAR_PLATAFORMA';
