export const OBTER_INSTITUICOES = 'OBTER_INSTITUICOES';
export const DELETE_INSTITUICAO = 'DELETE_INSTITUICAO';
export const ATUALIZAR_INSTITUICAO = 'ATUALIZAR_INSTITUICAO';
export const ACRESCENTAR_INSTITUICAO = 'ACRESCENTAR_INSTITUICAO';
