export const OBTER_INSTITUICOES = 'OBTER_INSTITUICOES';
export const DELETE_INSTITUICAO = 'DELETE_INSTITUICAO';
export const ATUALIZAR_INSTITUICAO = 'ATUALIZAR_INSTITUICAO';
export const ACRESCENTAR_INSTITUICAO = 'ACRESCENTAR_INSTITUICAO';
export const ESTADO_DIALOG = 'ESTADO_DIALOG';
export const INSTITUICAO_EDITAR = 'INSTITUICAO_EDITAR';
export const INSTITUICAO_ENCONTRADA = 'INSTITUICAO_ENCONTRADA';
