export const DEFINIR_NOTIFICACOES = 'DEFINIR_NOTIFICACOES';
export const REMOVER_NOTIFICACAO = 'REMOVER_NOTIFICACAO';
export const ATUALIZAR_NOTIFICACAO = 'ATUALIZAR_NOTIFICACAO';
export const ACRESCENTAR_NOTIFICACAO = 'ACRESCENTAR_NOTIFICACAO';
