export const OBTER_PONTO_DE_DOACOES = 'OBTER_PONTO_DE_DOACOES';
export const DELETE_PONTO_DE_DOACAO = 'DELETE_PONTO_DE_DOACAO';
export const ATUALIZAR_PONTO_DE_DOACAO = 'ATUALIZAR_PONTO_DE_DOACAO';
export const ACRESCENTAR_PONTO_DE_DOACAO = 'ACRESCENTAR_PONTO_DE_DOACAO';
export const GET_PONTO_BY_INSTITUICAO = 'GET_PONTO_BY_INSTITUICAO';
