export const OBTER_SISTEMAS = 'OBTER_SISTEMAS';
export const DELETE_SISTEMA = 'DELETE_SISTEMA';
export const ATUALIZAR_SISTEMA = 'ATUALIZAR_SISTEMA';
export const ACRESCENTAR_SISTEMA = 'ACRESCENTAR_SISTEMA';
